Question.create(content: 'Where was Lizzo born?')
Question.create(content: "What is Lizzo's given name?")
Question.create(content: "What musical instrument did Lizzo study in college?")
Question.create(content: "What was the name of Lizzo's first studio album?")
Question.create(content: "In what movie did Lizzo appear as an actress?")
Question.create(content: "In what part of Houston did Lizzo grow up?")
Question.create(content: "What is Lizzo's zodiac sign?")
Question.create(content: "What college did Lizzo attend?")
Question.create(content: "What is Lizzo's group of backup dancers called?")
Question.create(content: "What television show featured Lizzo's music?")
Question.create(content: "At what awards show was Lizzo nominated for 'Best Female Hip-Hop Artist?")
Question.create(content: "How tall is Lizzo?")
Question.create(content: "What famous musician did Lizzo collaborate with before their death?")
Question.create(content: "On what reality TV show was Lizzo a judge?")
Question.create(content: "With what other famous female hip-hop artist did Lizzo collaborate in 2019?")
Question.create(content: "What was Lizzo's first number one single?")
Question.create(content: "When Lizzo took a DNA test, she found out she was 100% what?")
Question.create(content: "What NPR dimunative concert series did Lizzo participate in?")
